### ISSUE TITLE
faster search

### ISSUE THREAD

**Issue by kawa-kokosowa** [kawa-kokosowa/bubblebbs#108]
search can be pretty slow! speed this up somehow!!!!!

**Comment by lily-mayfield** [comment]
hm wonder if i should start using postgres in docker container... probably... this is really slow. if that doesn't solve then i gotta do word matches not like matches

**Comment by lily-mayfield** [comment]
hm wonder if i should start using postgres in docker container... probably... this is really slow. if that doesn't solve then i gotta do word matches not like matches

**Comment by kawa-kokosowa** [comment]
Pretty much resolved in v0.1.21.
